
// This file contains only the raw data for navigation links, without any React components or icons.
// This allows it to be safely imported into server components for metadata generation without causing build errors.

export const CATEGORY_LINKS_DATA = [
  {
    label: 'Electronics',
    href: '/products/category/electronics',
    subLinks: [
      { label: 'Mobile Phones & Accessories', href: '/products/category/electronics/mobiles-accessories' },
      { label: 'Laptops & Computers', href: '/products/category/electronics/laptops-computers' },
      { label: 'TVs & Home Theater', href: '/products/category/electronics/tvs-home-theater' },
      { label: 'Audio & Headphones', href: '/products/category/electronics/audio-headphones' },
      { label: 'Cameras & Drones', href: '/products/category/electronics/cameras-drones' },
      { label: 'Gaming Consoles & Accessories', href: '/products/category/electronics/gaming' },
      { label: 'Wearable Technology', href: '/products/category/electronics/wearables' },
      { label: 'Printers & Scanners', href: '/products/category/electronics/printers-scanners' },
      { label: 'Home Appliances (Small)', href: '/products/category/electronics/small-appliances' },
      { label: 'Home Appliances (Large)', href: '/products/category/electronics/large-appliances' },
      { label: 'Data Storage', href: '/products/category/electronics/data-storage' },
      { label: 'Networking Devices', href: '/products/category/electronics/networking' },
    ],
  },
  {
    label: 'Fashion',
    href: '/products/category/fashion',
    subLinks: [
      { label: 'Men\'s Clothing', href: '/products/category/fashion/men-clothing' },
      { label: 'Women\'s Clothing', href: '/products/category/fashion/women-clothing' },
      { label: 'Kid\'s Fashion', href: '/products/category/fashion/kids-fashion' },
      { label: 'Men\'s Shoes', href: '/products/category/fashion/men-shoes' },
      { label: 'Women\'s Shoes', href: '/products/category/fashion/women-shoes' },
      { label: 'Kid\'s Shoes', href: '/products/category/fashion/kids-shoes' },
      { label: 'Bags & Luggage', href: '/products/category/fashion/bags-luggage' },
      { label: 'Watches', href: '/products/category/fashion/watches' },
      { label: 'Jewelry', href: '/products/category/fashion/jewelry' },
      { label: 'Eyewear', href: '/products/category/fashion/eyewear' },
      { label: 'Traditional Wear', href: '/products/category/fashion/traditional-wear' },
      { label: 'Sportswear & Activewear', href: '/products/category/fashion/sportswear' },
    ],
  },
  {
    label: 'Home & Living',
    href: '/products/category/home-living',
    subLinks: [
      { label: 'Furniture', href: '/products/category/home-living/furniture' },
      { label: 'Home Decor', href: '/products/category/home-living/decor' },
      { label: 'Kitchen & Dining', href: '/products/category/home-living/kitchen-dining' },
      { label: 'Bedding', href: '/products/category/home-living/bedding' },
      { label: 'Bath', href: '/products/category/home-living/bath' },
      { label: 'Storage & Organization', href: '/products/category/home-living/storage-organization' },
      { label: 'Lighting', href: '/products/category/home-living/lighting' },
      { label: 'Home Improvement & Tools', href: '/products/category/home-living/improvement-tools' },
      { label: 'Gardening & Outdoor', href: '/products/category/home-living/gardening-outdoor' },
      { label: 'Rugs & Carpets', href: '/products/category/home-living/rugs-carpets' },
    ],
  },
  {
    label: 'Beauty & Personal Care',
    href: '/products/category/beauty-personal-care',
    subLinks: [
      { label: 'Skincare', href: '/products/category/beauty-personal-care/skincare' },
      { label: 'Makeup', href: '/products/category/beauty-personal-care/makeup' },
      { label: 'Hair Care', href: '/products/category/beauty-personal-care/haircare' },
      { label: 'Fragrances', href: '/products/category/beauty-personal-care/fragrances' },
      { label: 'Personal Care Appliances', href: '/products/category/beauty-personal-care/appliances' },
      { label: 'Men\'s Grooming', href: '/products/category/beauty-personal-care/mens-grooming' },
      { label: 'Oral Care', href: '/products/category/beauty-personal-care/oral-care' },
      { label: 'Feminine Hygiene', href: '/products/category/beauty-personal-care/feminine-hygiene' },
    ],
  },
  {
    label: 'Sports & Outdoors',
    href: '/products/category/sports-outdoors',
    subLinks: [
      { label: 'Exercise & Fitness', href: '/products/category/sports-outdoors/exercise-fitness' },
      { label: 'Cycling', href: '/products/category/sports-outdoors/cycling' },
      { label: 'Camping & Hiking', href: '/products/category/sports-outdoors/camping-hiking' },
      { label: 'Team Sports Gear', href: '/products/category/sports-outdoors/team-sports' },
      { label: 'Outdoor Recreation', href: '/products/category/sports-outdoors/outdoor-recreation' },
      { label: 'Sportswear', href: '/products/category/sports-outdoors/sportswear' }, 
      { label: 'Water Sports', href: '/products/category/sports-outdoors/water-sports' },
      { label: 'Fitness Trackers', href: '/products/category/sports-outdoors/fitness-trackers' }, 
    ],
  },
  {
    label: 'Toys, Kids & Baby',
    href: '/products/category/toys-kids-baby',
    subLinks: [
      { label: 'Toys & Games', href: '/products/category/toys-kids-baby/toys-games' },
      { label: 'Baby Care & Essentials', href: '/products/category/toys-kids-baby/baby-care' },
      { label: 'Baby Gear (Strollers, Carriers)', href: '/products/category/toys-kids-baby/baby-gear' },
      { label: 'Nursery Furniture & Decor', href: '/products/category/toys-kids-baby/nursery' },
      { label: 'Kids\' Books', href: '/products/category/toys-kids-baby/kids-books' }, 
      { label: 'School Supplies for Kids', href: '/products/category/toys-kids-baby/school-supplies' }, 
    ],
  },
  {
    label: 'Automotive',
    href: '/products/category/automotive',
    subLinks: [
      { label: 'Car Care & Cleaning', href: '/products/category/automotive/car-care' },
      { label: 'Oils & Fluids', href: '/products/category/automotive/oils-fluids' },
      { label: 'Replacement Parts', href: '/products/category/automotive/parts' },
      { label: 'Tires & Wheels', href: '/products/category/automotive/tires-wheels' },
      { label: 'Interior Accessories', href: '/products/category/automotive/interior-accessories' },
      { label: 'Exterior Accessories', href: '/products/category/automotive/exterior-accessories' },
      { label: 'Motorcycle Gear', href: '/products/category/automotive/motorcycle-gear' },
    ],
  },
  {
    label: 'Books, Office & Stationery',
    href: '/products/category/books-office-stationery',
    subLinks: [
      { label: 'Books (Fiction, Non-fiction)', href: '/products/category/books-office-stationery/books' },
      { label: 'Children\'s Books', href: '/products/category/books-office-stationery/children-books' },
      { label: 'Magazines & Periodicals', href: '/products/category/books-office-stationery/magazines' },
      { label: 'Office Supplies', href: '/products/category/books-office-stationery/office-supplies' },
      { label: 'School Supplies', href: '/products/category/books-office-stationery/school-supplies' },
      { label: 'Writing Instruments', href: '/products/category/books-office-stationery/writing' },
      { label: 'Art Supplies', href: '/products/category/books-office-stationery/art-supplies' },
    ],
  },
  {
    label: 'Health & Wellness',
    href: '/products/category/health-wellness',
    subLinks: [
      { label: 'Vitamins & Supplements', href: '/products/category/health-wellness/vitamins-supplements' },
      { label: 'First Aid Supplies', href: '/products/category/health-wellness/first-aid' },
      { label: 'Personal Hygiene', href: '/products/category/health-wellness/personal-hygiene' }, 
      { label: 'Medical Equipment', href: '/products/category/health-wellness/medical-equipment' },
      { label: 'Optical Care', href: '/products/category/health-wellness/optical-care' },
      { label: 'Family Planning', href: '/products/category/health-wellness/family-planning' },
      { label: 'Mobility Aids', href: '/products/category/health-wellness/mobility-aids' },
    ],
  },
];
